language: node_js
node_js:
  - '12'
services:
  - mongodb
cache: npm
branches:
  only:
    - main
env:
  global:
    - PORT=3000
    - MONGODB_URL=mongodb://localhost:27017/backendd
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - npm run lint
  - npm run test
