version: '3'

services:
  backendd:
    build: .
    image: backendd
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/backendd
    networks:
      - backendd-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - backendd-network

volumes:
  dbdata:

networks:
  backendd-network:
    driver: bridge
